//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12/18/2021 4:23:03 PM
namespace LabLINQ
{
    
    /// <summary>
    /// There are no comments for STUDEntities in the schema.
    /// </summary>
    public partial class STUDEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new STUDEntities object using the connection string found in the 'STUDEntities' section of the application configuration file.
        /// </summary>
        public STUDEntities() : 
                base("name=STUDEntities", "STUDEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new STUDEntities object.
        /// </summary>
        public STUDEntities(string connectionString) : 
                base(connectionString, "STUDEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new STUDEntities object.
        /// </summary>
        public STUDEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "STUDEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for STUDENTS_ONE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<STUDENTS_ONE> STUDENTS_ONE
        {
            get
            {
                if ((this._STUDENTS_ONE == null))
                {
                    this._STUDENTS_ONE = base.CreateQuery<STUDENTS_ONE>("[STUDENTS_ONE]");
                }
                return this._STUDENTS_ONE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<STUDENTS_ONE> _STUDENTS_ONE;
        /// <summary>
        /// There are no comments for STUDENTS_ONE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSTUDENTS_ONE(STUDENTS_ONE sTUDENTS_ONE)
        {
            base.AddObject("STUDENTS_ONE", sTUDENTS_ONE);
        }
    }
    /// <summary>
    /// There are no comments for STUDModel.STUDENTS_ONE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="STUDModel", Name="STUDENTS_ONE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class STUDENTS_ONE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new STUDENTS_ONE object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static STUDENTS_ONE CreateSTUDENTS_ONE(int id)
        {
            STUDENTS_ONE sTUDENTS_ONE = new STUDENTS_ONE();
            sTUDENTS_ONE.Id = id;
            return sTUDENTS_ONE;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property SURNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string SURNAME
        {
            get
            {
                return this._SURNAME;
            }
            set
            {
                this.OnSURNAMEChanging(value);
                this.ReportPropertyChanging("SURNAME");
                this._SURNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SURNAME");
                this.OnSURNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _SURNAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSURNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSURNAMEChanged();
        /// <summary>
        /// There are no comments for property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for property PATRONIMIC in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PATRONIMIC
        {
            get
            {
                return this._PATRONIMIC;
            }
            set
            {
                this.OnPATRONIMICChanging(value);
                this.ReportPropertyChanging("PATRONIMIC");
                this._PATRONIMIC = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PATRONIMIC");
                this.OnPATRONIMICChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PATRONIMIC;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPATRONIMICChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPATRONIMICChanged();
        /// <summary>
        /// There are no comments for property GROUP_NUMBER in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string GROUP_NUMBER
        {
            get
            {
                return this._GROUP_NUMBER;
            }
            set
            {
                this.OnGROUP_NUMBERChanging(value);
                this.ReportPropertyChanging("GROUP_NUMBER");
                this._GROUP_NUMBER = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GROUP_NUMBER");
                this.OnGROUP_NUMBERChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _GROUP_NUMBER;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGROUP_NUMBERChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGROUP_NUMBERChanged();
        /// <summary>
        /// There are no comments for property ABSENSES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> ABSENSES
        {
            get
            {
                return this._ABSENSES;
            }
            set
            {
                this.OnABSENSESChanging(value);
                this.ReportPropertyChanging("ABSENSES");
                this._ABSENSES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ABSENSES");
                this.OnABSENSESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _ABSENSES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABSENSESChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnABSENSESChanged();
        /// <summary>
        /// There are no comments for property UNREASONABLE_ABSENSES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> UNREASONABLE_ABSENSES
        {
            get
            {
                return this._UNREASONABLE_ABSENSES;
            }
            set
            {
                this.OnUNREASONABLE_ABSENSESChanging(value);
                this.ReportPropertyChanging("UNREASONABLE_ABSENSES");
                this._UNREASONABLE_ABSENSES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UNREASONABLE_ABSENSES");
                this.OnUNREASONABLE_ABSENSESChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _UNREASONABLE_ABSENSES;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUNREASONABLE_ABSENSESChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUNREASONABLE_ABSENSESChanged();
        /// <summary>
        /// There are no comments for property UNREADY_LABS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> UNREADY_LABS
        {
            get
            {
                return this._UNREADY_LABS;
            }
            set
            {
                this.OnUNREADY_LABSChanging(value);
                this.ReportPropertyChanging("UNREADY_LABS");
                this._UNREADY_LABS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UNREADY_LABS");
                this.OnUNREADY_LABSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _UNREADY_LABS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUNREADY_LABSChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUNREADY_LABSChanged();
        /// <summary>
        /// There are no comments for property UNDONE_LABS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> UNDONE_LABS
        {
            get
            {
                return this._UNDONE_LABS;
            }
            set
            {
                this.OnUNDONE_LABSChanging(value);
                this.ReportPropertyChanging("UNDONE_LABS");
                this._UNDONE_LABS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UNDONE_LABS");
                this.OnUNDONE_LABSChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _UNDONE_LABS;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUNDONE_LABSChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUNDONE_LABSChanged();
        /// <summary>
        /// There are no comments for property UPDATE_COUNTER in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> UPDATE_COUNTER
        {
            get
            {
                return this._UPDATE_COUNTER;
            }
            set
            {
                this.OnUPDATE_COUNTERChanging(value);
                this.ReportPropertyChanging("UPDATE_COUNTER");
                this._UPDATE_COUNTER = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UPDATE_COUNTER");
                this.OnUPDATE_COUNTERChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _UPDATE_COUNTER;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUPDATE_COUNTERChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUPDATE_COUNTERChanged();
        /// <summary>
        /// There are no comments for property UPDATE_CALCULATED in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<double> UPDATE_CALCULATED
        {
            get
            {
                return this._UPDATE_CALCULATED;
            }
            set
            {
                this.OnUPDATE_CALCULATEDChanging(value);
                this.ReportPropertyChanging("UPDATE_CALCULATED");
                this._UPDATE_CALCULATED = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UPDATE_CALCULATED");
                this.OnUPDATE_CALCULATEDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<double> _UPDATE_CALCULATED;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUPDATE_CALCULATEDChanging(global::System.Nullable<double> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUPDATE_CALCULATEDChanged();
    }
}
